### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaLytvynov** [AntoninaSych/slider#2]
https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L52 - тут можно использовать обратные ковычки `` которые поддерживают строковый литерал и заменить на `<div class="slide ${activeSlide}" >` ну и для остальных тоже

**Comment by IlyaLytvynov** [comment]
https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L43 - вот это обращение можно удалить, если вместо wrapper.insertAdjacentHTML("afterbegin", html); использовать wrapper.innerHTML = html,
и можно https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L47 вынести в конструктор

**Comment by IlyaLytvynov** [comment]
https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L49 - тут я бы заменил for на forEach например https://gist.github.com/IlyaLytvynov/25d0d1e0ab67aa9c6a6690f9a4e7873d

**Comment by IlyaLytvynov** [comment]
Используй `` https://learn.javascript.ru/string#kavychki

**Comment by IlyaLytvynov** [comment]
https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L72 - все обращения к элементам лучше организовать в конструкторе document.get... 
ну и предпочтительно использовать document.querySelector() и привязываться к классу либо data атрибуту

**Comment by IlyaLytvynov** [comment]
this.prev.bind(this) - круто что ты знаешь bind, но в большинстве случаем лучше использовать () => {} 

`
document.getElementById('prev').addEventListener('click', () => this.prev());
`

**Comment by IlyaLytvynov** [comment]
И есть боль.... Смотри ты постоянно перерисовуешь все слайд, не надо так. все слайды создать один раз и ссылку на сам элемент сохранить в массиве, и потом удалять класс у одного и добавлять новому активному

**Comment by AntoninaSych** [comment]
> https://github.com/AntoninaSych/slider/blob/8b73fb5984151b7407a7f7dc82afd8f8764ec75f/js/slider.js#L72
> 
> - все обращения к элементам лучше организовать в конструкторе document.get...
> ну и предпочтительно использовать document.querySelector() и привязываться к классу либо data атрибуту
Объявила в конструкторе: 
       this.prevBtn = document.querySelector('#prev');
        this.nextBtn = document.querySelector('#next');
        this.toogleBtn = document.querySelector('#toogle'); ,
 но тут элемента нет на странице, так как он еще не отрисовался методом drawSlider() или есть какое-то еще решение и этой задачи?

**Comment by IlyaLytvynov** [comment]
https://github.com/AntoninaSych/slider/issues/2#issuecomment-559491872 - в твоем случае нужно сначала создать элементы( вызывать функцию отрисовки в конструкторе) и тебе не неужно будет их выбирать если создашь через document.createElement
